db:
  image: postgres:9.4
  restart: always
  expose:
    - 5432
  environment:
    POSTGRES_USER: "editor"
    POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"

editor:
  image: services-toolkit/editor
  ports:
   - "40001:8080"
  links:
    - db
    - engine
  environment:
    POSTGRES_USER: "editor"
    POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"
    ENGINE_LINK: "http://sinv-56064.edu.hsr.ch:40000"

engine:
  image: services-toolkit/engine
#  build: Engine/docker
  expose:
   - 8080
  ports:
   - "40000:8080"
